### PR TITLE
Support Google Cloud Spanner (GoogleSQL dialect)

### PR DESCRIPTION
**Pull request by rafi-rr**
This PR adds support for Spanner as an additional database option in parallel to BigQuery and PostgreSQL.
It accesses a Spanner instance and then is capable of using all databases within that instance as data sources.
Furthermore, the embeddings database is defined separately as a separate database.

### CODE REVIEW

**Review by 5Y5TEM — APPROVED** [review]
LGTM; Need to resolve conflicts

**Comment by rafi-rr** [comment]
Thanks @5Y5TEM 
Taking care of this now.

**Comment by rafi-rr** [comment]
@5Y5TEM Verified on my end following conflict resolution.

**Comment by 5Y5TEM** [comment]
@rafi-rr I have resolved all the issues and merged your code in the spanner branch: https://github.com/GoogleCloudPlatform/Open_Data_QnA/tree/spanner

Once the team is done with testing, we will merge it to main. 

Thank you for contributing! I will resolve this PR for now.

**Pull request closed without merging**
